name: 'CI'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  check-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - name: install Crow
        run: |
          wget https://github.com/CrowCpp/Crow/releases/download/v1.0%2B5/crow-v1.0+5.deb
          sudo apt install ./crow-v1.0+5.deb
      - name: Install ROS2
        uses: lf-lang/lingua-franca/.github/actions/setup-ros2@master
      - name: Setup ROS2
        run: | 
          source /opt/ros/*/setup.bash
          printenv
          printenv >> GITHUB_ENV
      - uses: lf-lang/action-check-lf-files@main
        with:
          check_mode: "compile"
          no_compile_flag: false
          exclude_dirs: '["failing", "experimental"]'
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - uses: lf-lang/action-check-lf-files@main
        with:
          check_mode: "format"
          exclude_dirs: '["failing", "experimental"]'
