name: 'CI'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  check-lf-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lf-lang/action-check-lf-files@new-parameters
        with:
          no-compile-flag: true
          exclude-dirs: '["failing", "experimental"]'
